name: Notify parent repo

on:
  push:
    branches:
      - main   # or whichever branch you want

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch event
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PARENT_REPO_TOKEN }}" \
            https://api.github.com/repos/yashgulati-sudo/cloudera-partners/dispatches \
            -d '{"event_type":"update-submodule"}'
